export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Login } from "./Login";
export { default as Admin} from "./Admin";
export { default as Employe} from "./Employe";
export { default as Client} from "./Client";
export { default as Register} from "./Register";
import { CookiesProvider } from "react-cookie";
